  export const HELP_PREFIX = 'http://docs.dominodatalab.com/';
export const ADMIN_HELP_PREFIX = 'https://admin.dominodatalab.com/';

export const SUPPORT_ARTICLE = {
  APP_PUBLISH_CORS: 'reference/publish/apps/cors.html',
  APP_PUBLISH_CSP: 'user_guide/aec000/content-security-policies-for-web-apps/',
  APP_PUBLISH_OVERVIEW: 'user_guide/71635d/publish-apps/',
  CC_DATA_EXPORT: 'admin_guide/9a12a0/export-control-center-data-with-the-api/',
  COMMENTS: 'user_guide/06ceeb/add-comments/',
  COMPUTE_AND_SPEND: 'admin_guide/d5d2ac/control-center/',
  COMPUTE_CLUSTER: 'user_guide/e6e601/workspaces/#clusters',
  COMPUTE_CLUSTER_MAX_EXECUTORS: 'admin_guide/eca4b2/manage-domino-compute-resources/#maximum-simultaneous-executions',
  DASK_CONFIG_PREREQUISITES: 'user_guide/747a51/on-demand-dask-overview/',
  DATASETS_ADMINISTRATION: 'admin_guide/ae1654/domino-datasets/',
  DATASETS_OVERVIEW: 'user_guide/0a8d11/datasets-overview/',
  DATASET_ROLES: 'user_guide/328a7c/dataset-roles/',
  DATA_SOURCES: 'user_guide/fbb41f/data-sources/',
  DIAGNOSTIC_STATS: 'user_guide/9e95a5/diagnostic-statistics-with-dominostats-json/',
  DOMINO_API: 'api_guide/f35c19/api-guide/',
  ENVIRONMENTS: 'user_guide/f51038/environment-management/',
  EXTERNAL_DATA_VOLUMES: 'user_guide/8ba49b/external-data-volumes/',
  EXTERNAL_DATA_VOLUMES_LINK: 'user_guide/8ba49b/external-data-volumes/',
  FEATURE_STORE_LINK: 'admin_guide/558c1d/set-up-the-feature-store/',
  FILE_RECOVERY_INFO_LINK: 'admin_guide/c29bdf/garbage-collection/#_salvaged_volumes',
  GBP__WORKING_WITH_ARTIFACTS: 'user_guide/de1f88/save-artifacts-to-the-domino-file-system/',
  GET_STARTED: 'get_started/index.html',
  GIT_CREDENTIALS: 'user_guide/910370/git-based-projects/',
  GIT_REPOSITORIES: 'user_guide/910370/git-based-projects/ ',
  JOBS__RERUN_JOBS: 'user_guide/121440/re-run-jobs/',
  MODEL_API_MONITORING_SET_UP: 'user_guide/2a7c3b/set-up-monitoring-for-model-apis/',
  MONITORING_FEATURE_SETS: 'user_guide/c97091/set-up-drift-detection/',
  MONITORING_MODEL_REGISTRATION: 'user_guide/93e5c0/set-up-prediction-capture/',
  MONITORING_TROUBLESHOOTING: 'user_guide/f66a1b/troubleshoot-the-model-monitor/',
  MPI_CONFIG_PREREQUISITES: 'user_guide/402c65/configure-mpi-prerequisites/',
  PROJECT_DEPENDENCIES: 'user_guide/e6ed48/export-and-import-project-content/',
  PROJECT_PORTFOLIO: 'admin_guide/6cde3a/project-stage-configuration/',
  PROJECT_SETUP_IGNORE_FILES: 'user_guide/bfeeae/set-up-your-project-to-ignore-files/',
  PUBLISH_MODELS: 'user_guide/8dbc91/deploy-models-at-rest/',
  PUBLISH_MODELS_OVERVIEW: 'user_guide/08a85b/deploy-models/',
  RAY_CONFIG_PREREQUISITES: 'user_guide/d13903/on-demand-ray-overview/',
  READ_WRITE_DATASETS: 'user_guide/0a8d11/datasets-overview/',
  RESTARTABLE_WORKSPACE_DELETE_MODAL_LINK: 'user_guide/a6aafd/delete-a-workspace/',
  RESTARTABLE_WORKSPACE_INFO_BANNER_LINK: 'user_guide/e6e601/workspaces/#_resume_a_workspace',
  RESTARTABLE_WORKSPACE_INFO_LINK: 'user_guide/e6e601/workspaces/',
  SCHEDULED_JOBS: 'user_guide/5dce1f/scheduled-jobs/',
  SPARK_CONFIG_PREREQUISITES: 'user_guide/1962f3/configure-prerequisites/',
  USER_MANAGEMENT_ADMIN_ROLES: 'admin_guide/2611b7/roles/',
  WORKING_FROM_COMMIT_ID: 'user_guide/f86aa5/working-from-a-commit-id-in-git/',
  WORKSPACES: 'user_guide/867b72/workspaces/',
  WORK_WITH_MPI_CLUSTER: 'user_guide/594e3c/work-with-your-cluster',
  EXPERIMENT_RUN_STATUS: 'user_guide/c6999f/manage-experiments/#_limitations',
  RESTRICT_ENVIRONMENT: 'admin_guide/0093e8/restricted-environments/#prevent_dynamic_installation',
  ENVIRONMENT_MODELS: 'user_guide/0e1396/model-apis/'
};
